development: &default
  adapter: postgresql
  database: s3bucketpolicy_development
  encoding: utf8
  host: localhost
  min_messages: warning
  pool: 2
  timeout: 5000

test:
  <<: *default
  database: s3bucketpolicy_test

staging:
  <<: *default
  url: 

production:
  <<: *default
  url: 
